build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:latest"
  amd64: "ghcr.io/home-assistant/amd64-base:latest"
  armhf: "ghcr.io/home-assistant/armhf-base:latest"
  armv7: "ghcr.io/home-assistant/armv7-base:latest"
  i386: "ghcr.io/home-assistant/i386-base:latest"
labels:
  org.opencontainers.image.title: "ntfy Home Assistant Add-on"
  org.opencontainers.image.description: "Self-hosted notification service"
  org.opencontainers.image.source: "https://github.com/michalchecinski/hassio-ntfy-sh-addon"
  org.opencontainers.image.licenses: "MIT"
args:
  NTFY_VERSION: "2.8.0"