#!/usr/bin/with-contenv bash

# ==============================================================================
# Home Assistant Community Add-on: ntfy
# Runs the ntfy notification service
# ==============================================================================

bashio::log.info "Starting ntfy..."

# Get configuration from add-on options
PORT=$(bashio::config 'port')
BASE_URL=$(bashio::config 'base_url')
AUTH_FILE=$(bashio::config 'auth_file')
AUTH_DEFAULT_ACCESS=$(bashio::config 'auth_default_access')
CACHE_FILE=$(bashio::config 'cache_file')
LOG_LEVEL=$(bashio::config 'log_level')
BEHIND_PROXY=$(bashio::config 'behind_proxy')
ENABLE_SIGNUP=$(bashio::config 'enable_signup')
ENABLE_LOGIN=$(bashio::config 'enable_login')
ENABLE_RESERVATIONS=$(bashio::config 'enable_reservations')

# Create configuration directory
mkdir -p /data/config

# Generate ntfy configuration file
CONFIG_FILE="/data/config/server.yml"

bashio::log.info "Generating ntfy configuration..."

cat > "${CONFIG_FILE}" <<EOF
# ntfy server configuration
# Generated by Home Assistant Add-on

# Listen address and port
listen-http: ":${PORT}"

# Base URL for the service
EOF

if [ -n "${BASE_URL}" ]; then
    echo "base-url: \"${BASE_URL}\"" >> "${CONFIG_FILE}"
fi

cat >> "${CONFIG_FILE}" <<EOF

# Cache settings
cache-file: "${CACHE_FILE}"
cache-duration: "12h"

# Log settings
log-level: ${LOG_LEVEL,,}
log-format: text

# Behind proxy settings
EOF

if [ "${BEHIND_PROXY}" = "true" ]; then
    cat >> "${CONFIG_FILE}" <<EOF
behind-proxy: true
EOF
fi

cat >> "${CONFIG_FILE}" <<EOF

# Authentication settings
EOF

if [ -n "${AUTH_FILE}" ] && [ "${AUTH_FILE}" != "" ]; then
    echo "auth-file: \"/data/${AUTH_FILE}\"" >> "${CONFIG_FILE}"
    echo "auth-default-access: \"${AUTH_DEFAULT_ACCESS}\"" >> "${CONFIG_FILE}"
    
    # Create auth file if it doesn't exist
    if [ ! -f "/data/${AUTH_FILE}" ]; then
        bashio::log.info "Creating authentication file: /data/${AUTH_FILE}"
        touch "/data/${AUTH_FILE}"
        chown ntfy:ntfy "/data/${AUTH_FILE}"
        chmod 600 "/data/${AUTH_FILE}"
    fi
else
    echo "auth-default-access: \"${AUTH_DEFAULT_ACCESS}\"" >> "${CONFIG_FILE}"
fi

# Web UI and signup settings
if [ "${ENABLE_SIGNUP}" = "true" ]; then
    echo "enable-signup: true" >> "${CONFIG_FILE}"
fi

if [ "${ENABLE_LOGIN}" = "true" ]; then
    echo "enable-login: true" >> "${CONFIG_FILE}"
fi

if [ "${ENABLE_RESERVATIONS}" = "true" ]; then
    echo "enable-reservations: true" >> "${CONFIG_FILE}"
fi

# CORS settings for Home Assistant integration
cat >> "${CONFIG_FILE}" <<EOF

# CORS settings
cors-allowed-origins: ["*"]

# Web app settings
web-root: disable

# Health check
enable-metrics: false
EOF

# Ensure data directory permissions
chown -R ntfy:ntfy /data
chmod -R 755 /data

# Log the configuration (without sensitive data)
bashio::log.info "ntfy configuration:"
bashio::log.info "Port: ${PORT}"
bashio::log.info "Log Level: ${LOG_LEVEL}"
bashio::log.info "Authentication: $([ -n "${AUTH_FILE}" ] && echo "Enabled" || echo "Disabled")"
bashio::log.info "Behind Proxy: ${BEHIND_PROXY}"

# Start ntfy server
bashio::log.info "Starting ntfy server..."
exec /usr/local/bin/ntfy serve --config="${CONFIG_FILE}"